# https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
# pip install sphinx

name: deploy-gh-pages
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Installing dependencies
      run: |
        pip install git+https://github.com/sphinx-doc/sphinx
        pip install sphinx_mdinclude sphinx-rtd-theme Pallets-Sphinx-Themes
        pip install numpydoc
    - name: Build
      run: make -C docs html

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
