name: CI
on: [push]

jobs:
  miniconda:
    name: Setup
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          python-version: 3.8
          auto-activate-base: true
          
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          
      - name: Install igm
        shell: bash -l {0}
        run: |
            pip install -e .
